### ISSUE TITLE
Enhance TurboRepo Firebase Example

### ISSUE THREAD

**Issue by Psycarlo** [Hacksore/turborepo-firebase-example#4]
Hello @Hacksore ,

This is a really good example for beginners to get started with turborepo and firebase - it has a great potential!

To make it even better, I would love to see a few more things:

- A `tsconfig` package, so we can share it across apps
- A `eslint-config` package
- An example for e2e testing (https://www.youtube.com/watch?v=bsE1VJn1HeU)
- Examples for unit and integration testing

Thanks!

**Comment by Hacksore** [comment]
I think all the things you listed are out of scope. This is not a template repo just more how you use turbo and firebase together.

You're welcome to create a template based on this with all the features you mentioned.
