### ISSUE TITLE
TypeError: async_hooks_1.AsyncLocalStorag

### ISSUE THREAD

**Issue by jason-liu22** [Hacksore/turborepo-firebase-example#5]
I cloned this repo, and I tried to run. it's working well.
But when I use the v2 of firebase function, it's not working.
I just change this one line.
`import * as functions from "firebase-functions";`
to
`import * as functions from "firebase-functions/v2";`
I am getting this error `TypeError: async_hooks_1.AsyncLocalStorag`
Can you please help me with this issue?

**Comment by Hacksore** [comment]
I got v2 working with the fix https://github.com/Hacksore/turborepo-firebase-example/commit/4d3bd14b2df15381a36f358b1c4124f6aa262b9f

![image](https://github.com/Hacksore/turborepo-firebase-example/assets/996134/312b0e17-1f98-4f96-8dc2-2e29862ee501)
